#
# Makefile for lzjb-stream's Doxygen documentation. Public domain.
#

.PHONY:	all clean

all:	lzjb-stream.doxyfile
	doxygen $^
	
# ----------------------------------------------------------------------

clean:
	rm -rf html
